baseURL = "https://scienceclouds.org/"
languageCode = "en-us"
title = "Cloud Computing for Science"

[outputFormats.FeaturedJSON]
mediaType = "application/json"
baseName = "featured"
isPlainText = true
notAlternative = true

[outputs]
home = ["HTML", "FeaturedJSON"]

[params]
description = "Cloud Computing for Science"
mainSections = ["posts"]

[taxonomies]
category = "categories"
author = "authors"

# Allow raw HTML in posts
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[services]
[services.googleAnalytics]
